language: cpp
branches:
  only:
  - "/^master$/"
  - "/^pre-release$/"
cache: ccache
compiler:
- gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
install:
- "[ $CC = gcc ] && export CC=gcc-6 || true"
- "[ $CXX = g++ ] && export CXX=g++-6 || true"
script:
- mkdir -p build && cd build && cmake .. && make && make test
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: qdAP+WVecRAZsxNm0DSfwkVwo9wLrVXNRDH0NSmmOS8EhLpDZ2uo9txlKBc8I+PHPOdKc/8BIO6KKv6I0EcKJzDmdyxIPJIFxX4zA+OrOoP1yrbBgY6Q8Aw2YeiCN0r3s02Jd/sYfT/YgB8prC6IsQogwNAgcgrBYtEVOfU9EQc9fXjgVO3w3//UtivzBhlLzqTM67TbH2SO56PDB64EgqjfoMT79l0dY3pnDiqGLp71py4jXeH3tve8CftNyyenRHwOT4kC6wFsaYGuh+EecN2ghQTcfDgMN73QVNHMKNePtKdWTyVGq1DysaGV6E5q3CJml9pGK/cU1pjnRxGA/wa+f0sqzqdjYC9eTtTFRa9QPoW5/l6SPR+bHnpiVntsZMzwKfbxM1g7bcb3OOBjzJ6B+LGuFjq6TEpMMcFB7H2tMb42ky6qz+UFwSVr+czm9uuAHSKdQ/dJWSD1IedI+DKcVnCyB/f6rv6s59HFxVapXxBFOCy4D5hIz/fBMevJ7+xYvyj6c/kyIg2i53o2cFKvhTmxx+2lHIrge33BnVocGfgeAEeWfF2zJ2ub5gQLE5yLt0tcGcAstUorf4F0nPxuQLvKjtsCTiYu5B+3gP68K2HwVWW3t8RSL1/uf+s3bnKA3p+OXdobJ/FhecnaW6aD6Mrjg/Oa/esV3oSaLwQ=
